In [1]:
import os

In [2]:
import sys

In [3]:
sys.path.append(os.getcwd() + '\\..')

In [4]:
from data.raw_data import *

In [5]:
import csv
import collections
def line_count(filename):
    result = 0
    for i, row in enumerate(csv.DictReader(open(filename)), start=1):
       result += 1
    return result

In [6]:
print('训练集size:{}'.format(line_count(train_file_path)))
print('测试集size:{}'.format(line_count(test_file_path)))

训练集size:40428967
测试集size:4577464

In [7]:
import pandas as pd

In [8]:
train_df = pd.read_csv(train_file_path, nrows=20)
test_df = pd.read_csv(test_file_path, nrows=20)

In [9]:
train_df.head(10)

,id,click,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,...,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
0,1000009418151094273,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,2,15706,320,50,1722,0,35,-1,79
1,10000169349117863715,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
2,10000371904215119486,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
3,10000640724480838376,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15706,320,50,1722,0,35,100084,79
4,10000679056417042096,0,14102100,1005,1,fe8cc448,9166c161,0569f928,ecad2386,7801e8d9,...,1,0,18993,320,50,2161,0,35,-1,157
5,10000720757801103869,0,14102100,1005,0,d6137915,bb1ef334,f028772b,ecad2386,7801e8d9,...,1,0,16920,320,50,1899,0,431,100077,117
6,10000724729988544911,0,14102100,1005,0,8fda644b,25d4cfcd,f028772b,ecad2386,7801e8d9,...,1,0,20362,320,50,2333,0,39,-1,157
7,10000918755742328737,0,14102100,1005,1,e151e245,7e091613,f028772b,ecad2386,7801e8d9,...,1,0,20632,320,50,2374,3,39,-1,23
8,10000949271186029916,1,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,2,15707,320,50,1722,0,35,-1,79
9,10001264480619467364,0,14102100,1002,0,84c7ba46,c4e18dd6,50e219e0,ecad2386,7801e8d9,...,0,0,21689,320,50,2496,3,167,100191,23

In [10]:
test_df.head(10)

,id,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,app_category,...,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
0,10000174058809263569,14103100,1005,0,235ba823,f6ebf28e,f028772b,ecad2386,7801e8d9,07d7df22,...,1,0,8330,320,50,761,3,175,100075,23
1,10000182526920855428,14103100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,...,1,0,22676,320,50,2616,0,35,100083,51
2,10000554139829213984,14103100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,...,1,0,22676,320,50,2616,0,35,100083,51
3,10001094637809798845,14103100,1005,0,85f751fd,c4e18dd6,50e219e0,51cedd4e,aefc06bd,0f2161f8,...,1,0,18648,320,50,1092,3,809,100156,61
4,10001377041558670745,14103100,1005,0,85f751fd,c4e18dd6,50e219e0,9c13b419,2347f47a,f95efa07,...,1,0,23160,320,50,2667,0,47,-1,221
5,10001521204153353724,14103100,1005,1,57fe1b20,5b626596,f028772b,ecad2386,7801e8d9,07d7df22,...,1,0,6563,320,50,572,2,39,-1,32
6,10001911056707023378,14103100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,...,1,0,22813,320,50,2647,2,39,100148,23
7,10001982898844213216,14103100,1005,0,85f751fd,c4e18dd6,50e219e0,388d9bfb,2347f47a,cef3e649,...,1,3,23214,300,250,2675,3,939,100058,100
8,10002000217531288531,14103100,1005,0,543a539e,c7ca3108,3e814130,ecad2386,7801e8d9,07d7df22,...,1,0,23642,320,50,2709,3,39,-1,23
9,10002107385290585663,14103100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,...,1,0,15699,320,50,1722,0,35,-1,79

In [11]:
def feature_num(columns, file_path):
    for column in columns:
        print(column + ' feature num:{}'.format(len(pd.read_csv(file_path, usecols=[column])[column].unique())))

In [12]:
feature_num(train_df.columns, train_file_path)

D:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2827: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

id feature num:40428967
click feature num:2
hour feature num:240
C1 feature num:7
banner_pos feature num:7
site_id feature num:4737
site_domain feature num:7745
site_category feature num:26
app_id feature num:8552
app_domain feature num:559
app_category feature num:36
device_id feature num:2686408
device_ip feature num:6729486
device_model feature num:8251
device_type feature num:5
device_conn_type feature num:4
C14 feature num:2626
C15 feature num:8
C16 feature num:9
C17 feature num:435
C18 feature num:4
C19 feature num:68
C20 feature num:172
C21 feature num:60

In [13]:
feature_num(test_df.columns, test_file_path)

D:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2827: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  if self.run_code(code, result):

id feature num:4577464
hour feature num:24
C1 feature num:7
banner_pos feature num:6
site_id feature num:2825
site_domain feature num:3366
site_category feature num:22
app_id feature num:3952
app_domain feature num:201
app_category feature num:28
device_id feature num:291759
device_ip feature num:1077199
device_model feature num:5438
device_type feature num:4
device_conn_type feature num:4
C14 feature num:1257
C15 feature num:8
C16 feature num:9
C17 feature num:240
C18 feature num:4
C19 feature num:47
C20 feature num:162
C21 feature num:39

In [14]:
import numpy as np
def column_feature_and_click_num(column):
    df = pd.read_csv(train_file_path, usecols=[column, 'click'])
    agg_df = df.groupby(column, as_index=False).agg({'click': [np.sum, np.size]})
    agg_df.columns = [column, 'sum', 'size']
    agg_df['ratio'] = agg_df['sum'] / agg_df['size']
    return agg_df.sort_values(by='ratio', axis=0, ascending=False)

In [15]:
column_feature_and_click_num('banner_pos')

   banner_pos      sum      size     ratio
6           7    13949     43577  0.320100
4           4     1428      7704  0.185358
1           1  2065164  11247282  0.183614
3           3      372      2035  0.182801
0           0  4781901  29109590  0.164272
5           5      702      5778  0.121495
2           2     1550     13001  0.119222

In [34]:
column_feature_and_click_num('hour')

         hour    sum    size     ratio
158  14102714  23064  105178  0.219285
60   14102312  32150  152413  0.210940
145  14102701  15892   75382  0.210820
50   14102302  30643  147980  0.207075
58   14102310  33612  162806  0.206454
103  14102507  28116  136398  0.206132
59   14102311  32980  161494  0.204218
216  14103000  17660   87333  0.202215
11   14102111  35476  175666  0.201951
124  14102604  30322  150184  0.201899
14   14102114  35168  174531  0.201500
159  14102715  20941  104242  0.200888
74   14102402  25082  125003  0.200651
217  14103001  18312   91307  0.200554
12   14102112  28775  143620  0.200355
169  14102801  20404  102748  0.198583
109  14102513  47052  238071  0.197639
61   14102313  31945  162221  0.196923
125  14102605  33337  171123  0.194813
157  14102713  33706  173052  0.194774
16   14102116  33469  171869  0.194736
234  14103018  31064  159570  0.194673
123  14102603  21766  112022  0.194301
235  14103019  26046  134243  0.194021
160  14102716  34780  179656  0.193592
15   14102115  34080  176156  0.193465
122  14102602  19488  100821  0.193293
49   14102301  19761  102258  0.193246
26   14102202  19847  102844  0.192982
65   14102317  30402  158332  0.192014
..        ...    ...     ...       ...
69   14102321  17159  116964  0.146703
189  14102821  24375  166216  0.146647
192  14102900  14492   98950  0.146458
29   14102205  41921  286697  0.146221
182  14102814  56588  387453  0.146051
197  14102905  19194  131740  0.145696
191  14102823  16506  113551  0.145362
32   14102208  46487  322803  0.144010
190  14102822  17865  124195  0.143846
188  14102820  24367  170081  0.143267
178  14102810  36710  258656  0.141926
95   14102423   3628   25622  0.141597
99   14102503   9524   67443  0.141216
202  14102910  31519  224107  0.140643
187  14102819  28165  201072  0.140074
34   14102210  61188  438270  0.139613
33   14102209  62410  447783  0.139376
201  14102909  25929  186264  0.139206
92   14102420   3183   23124  0.137649
36   14102212  56117  408650  0.137323
181  14102813  59080  432308  0.136662
221  14103005  33053  244765  0.135040
35   14102211  52218  386757  0.135015
37   14102213  43191  323480  0.133520
93   14102421   2669   20367  0.131045
176  14102808  37915  291763  0.129951
177  14102809  40643  328576  0.123694
91   14102419   4083   34163  0.119515
98   14102502   4443   38400  0.115703
220  14103004  36979  347806  0.106321

[240 rows x 4 columns]

In [17]:
column_feature_and_click_num('C1')

     C1      sum      size     ratio
1  1002   467995   2220812  0.210731
6  1012    19580    113512  0.172493
2  1005  6289056  37140632  0.169331
4  1008      704      5787  0.121652
5  1010    86023    903457  0.095215
3  1007     1392     35304  0.039429
0  1001      316      9463  0.033393

In [18]:
column_feature_and_click_num('site_category')

   site_category      sum      size     ratio
22      dedf689d    12593     24500  0.514000
4       3e814130   863245   3050306  0.283003
5       42a36e14      581      2515  0.231014
2       28905ebd  1534600   7377208  0.208019
24      f028772b  2272940  12657073  0.179579
11      74073276        2        14  0.142857
9       70fb0e29     3298     24224  0.136146
6       50e219e0  2126350  16537234  0.128580
19      c0dd3be3     4714     42090  0.111998
12      75fa27f6    17915    160985  0.111284
7       5378d028       46       483  0.095238
3       335d28a8    12779    136463  0.093644
23      e787de0e       89      1209  0.073615
10      72722551     1626     28216  0.057627
0       0569f928      923     17106  0.053958
18      bcf865d9       48      1045  0.045933
25      f66779e6    10019    252451  0.039687
13      76b2941d     3170    104754  0.030261
14      8fd0aea4      111      7482  0.014836
15      9ccfa2ea        4       318  0.012579
17      a818d37a       13      3230  0.004025
16      a72a0145        0         2  0.000000
20      c706e647        0        28  0.000000
21      da34532e        0        23  0.000000
1       110ab22d        0         6  0.000000
8       6432c423        0         2  0.000000

In [19]:
column_feature_and_click_num('app_category')

   app_category      sum      size     ratio
22     8df2e842      436      1679  0.259678
34     f95efa07   282664   1141673  0.247588
16     71af18ce        1         5  0.200000
0      07d7df22  5210822  26165592  0.199148
3      0d82db25        4        25  0.160000
31     dc97ec06     8552     54644  0.156504
5      0f9a328c      867      5584  0.155265
1      09481d60     8518     54886  0.155194
24     a7fd01ec       55       362  0.151934
9      4681bb9d      908      6291  0.144333
25     a86a3e89      325      2497  0.130156
11     4ce2e9fc     2570     20762  0.123784
30     d1327cf5    15197    123233  0.123319
4      0f2161f8  1033720   9561058  0.108118
20     879c24eb     1339     12785  0.104732
17     75d80bbe     3849     40108  0.095966
29     cef3e649   161450   1731545  0.093240
21     8ded1f7a   132021   1467257  0.089978
6      18b1e0be       15       212  0.070755
18     79f0b860       35       605  0.057851
35     fc6fa53d     1148     23663  0.048515
23     a3c42688      525     11121  0.047208
8      2fc4f2aa        4       234  0.017094
2      0bfbc358        7       425  0.016471
7      2281a340       30      2243  0.013375
15     7113d72a        3       304  0.009868
13     5326cf99        1       133  0.007519
19     86c1a5a3        0         3  0.000000
14     6fea3693        0         2  0.000000
12     52de74cf        0         1  0.000000
26     bd41f328        0         6  0.000000
27     bf8ac856        0         9  0.000000
28     cba0e20d        0         1  0.000000
10     4b7ade46        0        16  0.000000
32     ef03ae90        0         2  0.000000
33     f395a87f        0         1  0.000000

In [20]:
column_feature_and_click_num('device_type')

   device_type      sum      size     ratio
0            0   467995   2220812  0.210731
1            1  6311046  37304667  0.169176
3            4    73900    774272  0.095444
4            5    12123    129185  0.093842
2            2        2        31  0.064516

In [21]:
column_feature_and_click_num('device_conn_type')

   device_conn_type      sum      size     ratio
0                 0  6318889  34886838  0.181125
1                 2   448815   3317443  0.135289
2                 3    96092   2181796  0.044043
3                 5     1270     42890  0.029611

In [22]:
column_feature_and_click_num('C15')

    C15      sum      size     ratio
6   768      690      1621  0.425663
2   300   839925   2337294  0.359358
4   480      572      2137  0.267665
7  1024      652      2560  0.254688
3   320  5980935  37708959  0.158608
1   216    37988    298794  0.127138
5   728     4246     74533  0.056968
0   120       58      3069  0.018899

In [23]:
column_feature_and_click_num('C16')

    C16      sum      size     ratio
8  1024      690      1621  0.425663
4   250   761093   1806334  0.421347
5   320      572      2137  0.267665
7   768      652      2560  0.254688
6   480    22178    103365  0.214560
2    50  6037589  38136554  0.158315
1    36    37988    298794  0.127138
3    90     4246     74533  0.056968
0    20       58      3069  0.018899

In [24]:
column_feature_and_click_num('C18')

   C18      sum      size     ratio
2    2  2099065   7116058  0.294976
0    0  2680172  16939044  0.158225
3    3  1992882  13654242  0.145953
1    1    92947   2719623  0.034176

In [25]:
column_feature_and_click_num('C19')

     C19      sum      size     ratio
67  1959        1         2  0.500000
54  1071    10056     21210  0.474116
52  1063   185939    522944  0.355562
59  1447       56       161  0.347826
21   303   102855    328180  0.313410
49   939     1587      5421  0.292750
27   431   105978    430005  0.246458
4     39  2155820   8829426  0.244163
58  1327   253404   1092601  0.231927
57  1319    90402    394524  0.229142
63  1711    21436     94378  0.227129
17   291    54422    259205  0.209957
32   555     1724      8954  0.192540
40   687   104660    555698  0.188340
8     47   257334   1451708  0.177263
3     38    31878    182787  0.174400
2     35  2030102  12170630  0.166803
28   545       19       117  0.162393
11   167   509009   3145695  0.161811
53  1065    15959    101264  0.157598
51  1059    16575    110043  0.150623
29   547    35294    247633  0.142525
16   290     6256     44822  0.139574
1     34    36072    263275  0.137013
30   551     6917     52348  0.132135
35   675    11625     88549  0.131283
65  1835     2312     18756  0.123267
61  1575     2359     19196  0.122890
14   175    99171    811516  0.122205
12   169    35502    291959  0.121599
..   ...      ...       ...       ...
13   171    31087    306934  0.101282
15   289      579      5788  0.100035
62  1583      332      3477  0.095485
66  1839     1074     11315  0.094918
10   163    87527    926864  0.094433
64  1831     2209     23662  0.093356
6     43    19629    212757  0.092260
39   683       71       808  0.087871
50   943     1679     19128  0.087777
34   673     2152     24745  0.086967
41   801     2494     29418  0.084778
25   425     1453     17705  0.082067
42   803    30879    406539  0.075956
20   299    21904    291844  0.075054
60  1451     9917    135003  0.073458
19   297    74031   1014859  0.072947
48   937     8764    122660  0.071450
26   427    17756    270146  0.065727
24   423     1510     23111  0.065337
43   809     6223    100060  0.062193
0     33    29473    478227  0.061630
56  1315     2402     39870  0.060246
31   553      370      8087  0.045752
23   419    13664    325027  0.042040
22   417      255      6507  0.039189
18   295      959     27526  0.034840
7     45       80      3269  0.024472
9    161    36795   1587765  0.023174
55  1195        2       132  0.015152
36   677        0         8  0.000000

[68 rows x 4 columns]

In [16]:
column_feature_and_click_num('C21')

    C21      sum     size     ratio
8    33   589917  1497559  0.393919
9    35    13286    46707  0.284454
15   52   325717  1203050  0.270743
23   82    18997    71393  0.266091
3    16    90093   347178  0.259501
7    32   410781  1783343  0.230343
6    23  1894394  8896205  0.212944
1    13    81705   384314  0.212600
2    15   161746   766986  0.210885
25   90    27009   128679  0.209894
39  117    86383   419943  0.205702
59  255      906     4608  0.196615
32  102     1724     8954  0.192540
22   79   866402  4614799  0.187744
14   51   157689   850249  0.185462
58  253    14300    78375  0.182456
19   70    23006   133539  0.172279
54  221   846996  5051245  0.167681
28   94     3625    22206  0.163244
49  194     2092    14032  0.149088
34  108     6793    46723  0.145389
24   85       72      497  0.144869
38  116     2251    16189  0.139045
13   48   298311  2160794  0.138056
18   69    24268   176226  0.137710
0     1      416     3027  0.137430
29   95    34238   276988  0.123608
17   68    38543   324148  0.118906
10   42   120256  1018906  0.118025
43  159    33865   290215  0.116689
30  100     7538    65258  0.115511
42  157   214131  1856105  0.115366
37  112     8183    74532  0.109792
48  182     5458    49761  0.109684
57  251     2195    21170  0.103684
36  111    14399   140305  0.102626
31  101     8111    81352  0.099703
12   46    23316   235809  0.098877
45  171    11257   115845  0.097173
27   93     1176    12411  0.094755
26   91    15844   169042  0.093728
4    17    15100   166268  0.090817
5    20     1204    13365  0.090086
46  177      443     5618  0.078854
55  229    30879   406539  0.075956
11   43    44593   588961  0.075715
47  178     3654    50055  0.073000
41  156    23552   334906  0.070324
53  219      121     1765  0.068555
33  104      575     8425  0.068249
16   61   135378  2053636  0.065921
40  126      508     7780  0.065296
35  110     7793   121407  0.064189
50  195      243     3890  0.062468
52  212    34201   659994  0.051820
21   76     7001   138160  0.050673
56  246     9346   201746  0.046326
44  163      255     6507  0.039189
51  204     3370    92782  0.036322
20   71    59461  2108496  0.028201

In [28]:
def column_feature_and_click_num2(column, topn):
    return pd.read_csv(train_file_path, usecols=[column])[column].value_counts()[:topn]

In [29]:
column_feature_and_click_num2('device_id', 10)

a99f214a    33358308
0f7c61dc       21356
c357dbff       19667
936e92fb       13712
afeffc18        9654
987552d1        4187
28dc8687        4101
d857ffbb        4004
cef4c8cc        3694
b09da1c4        3655
Name: device_id, dtype: int64

In [30]:
column_feature_and_click_num2('device_ip', 10)

6b9769f2    208701
431b3174    135322
2f323f36     88499
af9205f9     87844
930ec31d     86996
af62faf4     85802
009a7861     85382
285aa37d     85313
6394f6f6     83184
d90a7774     82980
Name: device_ip, dtype: int64

In [31]:
column_feature_and_click_num2('site_id', 10)

85f751fd    14596137
1fbe01fe     6486150
e151e245     2637747
d9750ee7      963745
5b08c53b      913325
5b4d2eda      771360
856e6d3f      765891
a7853007      461311
b7e9786d      369099
5ee41ff2      349008
Name: site_id, dtype: int64

In [32]:
column_feature_and_click_num2('app_id', 10)

ecad2386    25832830
92f5800b     1555283
e2fcccd2     1129016
febd1138      759098
9c13b419      757812
7358e05e      615635
a5184c22      491457
d36838b1      457572
685d1c4c      408515
54c5d545      397693
Name: app_id, dtype: int64

In [33]:
14596137 + 25832830

40428967