In [2]:
import os

In [3]:
import sys

In [4]:
sys.path.append(os.getcwd() + '\\..')

In [5]:
from data.raw_data import *

In [6]:
import csv
import collections
def line_count(filename):
    result = 0
    for i, row in enumerate(csv.DictReader(open(filename)), start=1):
       result += 1
    return result

In [8]:
print('训练集size:{}'.format(line_count(train_file_path)))
print('测试集size:{}'.format(line_count(test_file_path)))

训练集size:40428967
测试集size:4577464

In [7]:
import pandas as pd

In [8]:
train_df = pd.read_csv(train_file_path, nrows=20)
test_df = pd.read_csv(test_file_path, nrows=20)

In [11]:
train_df.head(10)

,id,click,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,...,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
0,1000009418151094273,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,2,15706,320,50,1722,0,35,-1,79
1,10000169349117863715,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
2,10000371904215119486,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15704,320,50,1722,0,35,100084,79
3,10000640724480838376,0,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,0,15706,320,50,1722,0,35,100084,79
4,10000679056417042096,0,14102100,1005,1,fe8cc448,9166c161,0569f928,ecad2386,7801e8d9,...,1,0,18993,320,50,2161,0,35,-1,157
5,10000720757801103869,0,14102100,1005,0,d6137915,bb1ef334,f028772b,ecad2386,7801e8d9,...,1,0,16920,320,50,1899,0,431,100077,117
6,10000724729988544911,0,14102100,1005,0,8fda644b,25d4cfcd,f028772b,ecad2386,7801e8d9,...,1,0,20362,320,50,2333,0,39,-1,157
7,10000918755742328737,0,14102100,1005,1,e151e245,7e091613,f028772b,ecad2386,7801e8d9,...,1,0,20632,320,50,2374,3,39,-1,23
8,10000949271186029916,1,14102100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,...,1,2,15707,320,50,1722,0,35,-1,79
9,10001264480619467364,0,14102100,1002,0,84c7ba46,c4e18dd6,50e219e0,ecad2386,7801e8d9,...,0,0,21689,320,50,2496,3,167,100191,23

In [12]:
test_df.head(10)

,id,hour,C1,banner_pos,site_id,site_domain,site_category,app_id,app_domain,app_category,...,device_type,device_conn_type,C14,C15,C16,C17,C18,C19,C20,C21
0,10000174058809263569,14103100,1005,0,235ba823,f6ebf28e,f028772b,ecad2386,7801e8d9,07d7df22,...,1,0,8330,320,50,761,3,175,100075,23
1,10000182526920855428,14103100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,...,1,0,22676,320,50,2616,0,35,100083,51
2,10000554139829213984,14103100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,...,1,0,22676,320,50,2616,0,35,100083,51
3,10001094637809798845,14103100,1005,0,85f751fd,c4e18dd6,50e219e0,51cedd4e,aefc06bd,0f2161f8,...,1,0,18648,320,50,1092,3,809,100156,61
4,10001377041558670745,14103100,1005,0,85f751fd,c4e18dd6,50e219e0,9c13b419,2347f47a,f95efa07,...,1,0,23160,320,50,2667,0,47,-1,221
5,10001521204153353724,14103100,1005,1,57fe1b20,5b626596,f028772b,ecad2386,7801e8d9,07d7df22,...,1,0,6563,320,50,572,2,39,-1,32
6,10001911056707023378,14103100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,...,1,0,22813,320,50,2647,2,39,100148,23
7,10001982898844213216,14103100,1005,0,85f751fd,c4e18dd6,50e219e0,388d9bfb,2347f47a,cef3e649,...,1,3,23214,300,250,2675,3,939,100058,100
8,10002000217531288531,14103100,1005,0,543a539e,c7ca3108,3e814130,ecad2386,7801e8d9,07d7df22,...,1,0,23642,320,50,2709,3,39,-1,23
9,10002107385290585663,14103100,1005,0,1fbe01fe,f3845767,28905ebd,ecad2386,7801e8d9,07d7df22,...,1,0,15699,320,50,1722,0,35,-1,79

In [9]:
def feature_num(columns, file_path):
    for column in columns:
        print(column + ' feature num:{}'.format(len(pd.read_csv(file_path, usecols=[column])[column].unique())))

In [18]:
feature_num(train_df.columns, train_file_path)

id feature num:40428967
click feature num:2
hour feature num:240
C1 feature num:7
banner_pos feature num:7
site_id feature num:4737
site_domain feature num:7745
site_category feature num:26
app_id feature num:8552
app_domain feature num:559
app_category feature num:36
device_id feature num:2686408
device_ip feature num:6729486
device_model feature num:8251
device_type feature num:5
device_conn_type feature num:4
C14 feature num:2626
C15 feature num:8
C16 feature num:9
C17 feature num:435
C18 feature num:4
C19 feature num:68
C20 feature num:172
C21 feature num:60

In [19]:
feature_num(test_df.columns, test_file_path)

id feature num:4577464
hour feature num:24
C1 feature num:7
banner_pos feature num:6
site_id feature num:2825
site_domain feature num:3366
site_category feature num:22
app_id feature num:3952
app_domain feature num:201
app_category feature num:28
device_id feature num:291759
device_ip feature num:1077199
device_model feature num:5438
device_type feature num:4
device_conn_type feature num:4
C14 feature num:1257
C15 feature num:8
C16 feature num:9
C17 feature num:240
C18 feature num:4
C19 feature num:47
C20 feature num:162
C21 feature num:39

In [26]:
import numpy as np
def column_feature_and_click_num(column):
    df = pd.read_csv(train_file_path, usecols=[column, 'click'])
    agg_df = df.groupby(column, as_index=False).agg({'click': [np.sum, np.size]})
    agg_df.columns = [column, 'sum', 'size']
    agg_df['ratio'] = agg_df['sum'] / agg_df['size']
    return agg_df.sort_values(by='ratio', axis=0, ascending=False)

In [27]:
column_feature_and_click_num('banner_pos')

   banner_pos      sum      size     ratio
6           7    13949     43577  0.320100
4           4     1428      7704  0.185358
1           1  2065164  11247282  0.183614
3           3      372      2035  0.182801
0           0  4781901  29109590  0.164272
5           5      702      5778  0.121495
2           2     1550     13001  0.119222